### PR TITLE
Fixes #37. Redo folders to use src dir and put dist in root

### LINKED ISSUE #37: `Let` not yet supported in strict mode in Safari 9
I'm getting an error in Safari 9.1.1 when I include the inert.js file. I want to test dialogs with Voiceover, which is how I ran into this issue. 

Here's the error:
```
inert.js:93 
SyntaxError: Unexpected use of reserved word 'let' in strict mode
```

I saw some stuff in another issue about transpiling for other browsers. Do I need to do anything special with the polyfill to get it to work with Safari?

Thanks 😺

### PR DESCRIPTION
**Pull request by robdodson**
@alice PTAL

### CODE REVIEW

File: dist/inert.js [hunk 1]
```diff
@@ -926,5 +926,4 @@ function _classCallCheck(instance, Constructor) { if (!(instance instanceof Cons
...
...ZXJ0XSB7XFxuXCIgK1xuICAgICAgICAgICAgICAgICAgICAgIFwiICBwb2ludGVyLWV2ZW50czogbm9uZTtcXG5cIiArXG4gICAgICAgICAgICAgICAgICAgICAgXCIgIGN1cnNvcjogZGVmYXVsdDtcXG5cIiArXG4gICAgICAgICAgICAgICAgICAgICAgXCJ9XFxuXCIgK1xuICAgICAgICAgICAgICAgICAgICAgIFwiXFxuXCIgK1xuICAgICAgICAgICAgICAgICAgICAgIFwiW2luZXJ0XSwgW2luZXJ0XSAqIHtcXG5cIiArXG4gICAgICAgICAgICAgICAgICAgICAgXCIgIHVzZXItc2VsZWN0OiBub25lO1xcblwiICtcbiAgICAgICAgICAgICAgICAgICAgICBcIiAgLXdlYmtpdC11c2VyLXNlbGVjdDogbm9uZTtcXG5cIiArXG4gICAgICAgICAgICAgICAgICAgICAgXCIgIC1tb3otdXNlci1zZWxlY3Q6IG5vbmU7XFxuXCIgK1xuICAgICAgICAgICAgICAgICAgICAgIFwiICAtbXMtdXNlci1zZWxlY3Q6IG5vbmU7XFxuXCIgK1xuICAgICAgICAgICAgICAgICAgICAgIFwifVxcblwiO1xuICBub2RlLmFwcGVuZENoaWxkKHN0eWxlKTtcbn1cblxuY29uc3QgaW5lcnRNYW5hZ2VyID0gbmV3IEluZXJ0TWFuYWdlcihkb2N1bWVudCk7XG5cbk9iamVjdC5kZWZpbmVQcm9wZXJ0eShFbGVtZW50LnByb3RvdHlwZSwgJ2luZXJ0Jywge1xuICAgICAgICAgICAgICAgICAgICAgICAgZW51bWVyYWJsZTogdHJ1ZSxcbiAgICAgICAgICAgICAgICAgICAgICAgIGdldDogZnVuY3Rpb24oKSB7IHJldHVybiB0aGlzLmhhc0F0dHJpYnV0ZSgnaW5lcnQnKTsgfSxcbiAgICAgICAgICAgICAgICAgICAgICAgIHNldDogZnVuY3Rpb24oaW5lcnQpIHsgaW5lcnRNYW5hZ2VyLnNldEluZXJ0KHRoaXMsIGluZXJ0KSB9XG4gICAgICAgICAgICAgICAgICAgICAgfSk7XG5cbn0pKGRvY3VtZW50KTtcbiJdfQ==
```
Comment (alice) [inline dist/inert.js]: Cool
